package ro.etti.pki.platform.config.properties;

import jakarta.validation.constraints.NotBlank;

/**
 * Certificate Authority properties: location and credentials of the
 * Root CA PKCS#12 keystore.
 * <p>
 * Binds the {@code pki.ca:} section of {@code application.yml}.
 * Sensitive values ({@code keystorePassword}, {@code keyAlias}) come from
 * environment variables defined in {@code .env} (gitignored), never committed.
 * </p>
 */
public class CaProperties {

    /**
     * Path to the PKCS#12 keystore holding the Root CA private key and
     * certificate. Relative to the application's working directory (in dev:
     * the monorepo root). Generated by {@code scripts/generate-ca.sh}.
     */
    @NotBlank
    private String keystorePath;

    /**
     * Password used to open the PKCS#12 keystore.
     * Stored in {@code .env}, never in the repository.
     */
    @NotBlank
    private String keystorePassword;

    /**
     * Alias of the keystore entry that holds the CA key/certificate.
     */
    @NotBlank
    private String keyAlias;

    public CaProperties() {
    }

    public String getKeystorePath() {
        return keystorePath;
    }

    public void setKeystorePath(String keystorePath) {
        this.keystorePath = keystorePath;
    }

    public String getKeystorePassword() {
        return keystorePassword;
    }

    public void setKeystorePassword(String keystorePassword) {
        this.keystorePassword = keystorePassword;
    }

    public String getKeyAlias() {
        return keyAlias;
    }

    public void setKeyAlias(String keyAlias) {
        this.keyAlias = keyAlias;
    }
}
